Repository wanted-luckyzzang/wanted-doublenc, pull requests merged in 2022-02, with the labels that each got.

#10 refactor: styleReturn util 함수 수정
  utils/styleReturn.ts
Labels: refactor

#11 feat: slickSlider 컴포넌트 구현
  components/slickSlider/Button.tsx
  components/slickSlider/SlickSlider.tsx
  components/slickSlider/Slide.tsx
  public/images/sliderImage1.svg
Labels: feat

#12 Feat/types
  constants/color.ts
  constants/fontSize.ts
  constants/fontWeight.ts
  constants/iconSize.ts
  constants/index.ts
  types/index.ts
  types/styled.ts
Labels: feat, chore

#13 remove: 폴더명 수정하기위해 임시로 지움
  constants/color.ts
  constants/fontSize.ts
  constants/fontWeight.ts
  constants/iconSize.ts
  constants/index.ts
Labels: remove

#14 Style/dir
  components/common/Row.tsx
  pages/_app.tsx
  pages/index.tsx
  src/components/common/Col.tsx
  src/components/common/Img.tsx
  src/components/common/Row.tsx
  src/components/common/Text.tsx
  src/components/common/Title.tsx
  src/components/common/index.ts
  src/components/slickSlider/Button.tsx
  src/components/slickSlider/SlickSlider.tsx
  src/components/slickSlider/Slide.tsx
  src/constants/Color.ts
  src/constants/FontSize.ts
  src/constants/FontWeight.ts
  src/constants/IconSize.ts
  src/constants/index.ts
  src/hooks/.gitkeep
  src/store/index.ts
  src/store/modal.ts
  src/styles/GlobalStyle.ts
  src/types/index.ts
  src/types/modal.ts
  src/types/styled.ts
  src/utils/.gitkeep
  src/utils/index.ts
  src/utils/styleReturn.ts
  tsconfig.json
Labels: rename

#15 chore: API 주소를 감추기 위해 rewrite 적용
  .env
  next.config.js
Labels: chore

#16 chore: BASE_URL env 등록
  .env
Labels: chore

#17 feat: [redux] brand, category store 추가
  src/store/brand.ts
  src/store/category.ts
  src/store/index.ts
  src/types/index.ts
  src/types/store/brand.ts
  src/types/store/category.ts
  src/types/store/index.ts
  src/types/store/modal.ts
Labels: feat

#18 feat: 카테고리 정보 전역 state에 저장
  pages/index.tsx
  src/store/brand.ts
  src/store/category.ts
  src/store/index.ts
  src/types/index.ts
  src/types/store/brand.ts
  src/types/store/category.ts
  src/types/store/index.ts
Labels: feat

#20 refactor: reducer 초기 데이터 타입 변경
  pages/index.tsx
  src/components/common/Img.tsx
  src/store/brand.ts
  src/store/category.ts
  src/store/index.ts
Labels: refactor

#19 feat: Header 컴포넌트 추가
  public/images/hamberger.svg
  src/components/Header.tsx
  src/components/common/Text.tsx
Labels: feat

#21 design: 화면 가운데로 오게 스타일 변경
  src/components/Header.tsx
Labels: design

#22 feat: BackgroundColor 상수 추가
  src/constants/BackgroundColor.ts
  src/constants/index.ts
Labels: feat

#23 feat: 카테고리 컴포넌트 추가
  src/components/category/Card.tsx
  src/components/category/Category.tsx
  src/components/slickSlider/SlickSlider.tsx
Labels: feat

#24 design: 중앙정렬 제거
  src/components/Header.tsx
Labels: design

#26 design: Header, Card부분 스타일 수정
  pages/index.tsx
  src/components/Header.tsx
  src/components/category/Card.tsx
  src/components/category/Category.tsx
  src/constants/BackgroundColor.ts
  src/styles/GlobalStyle.ts
Labels: design

#27 Feat/ddang
  .env
  .gitignore
  pages/index.tsx
  src/components/category/Card.tsx
  src/components/category/index.ts
  src/components/ddang/Card.tsx
  src/components/ddang/DDang.tsx
  src/components/ddang/MenuTitle.tsx
  src/components/ddang/index.ts
  src/components/slickSlider/SlickSlider.tsx
  src/components/slickSlider/index.ts
Labels: feat

#25 feat: slider 자동으로 slide 변경
  pages/index.tsx
  src/components/slickSlider/SlickSlider.tsx
Labels: feat

#29 fix: map돌릴때 key값 안넣어서 났던 에러 해결
  src/components/category/Category.tsx
  src/components/ddang/DDang.tsx
Labels: fix

#30 Feat/categories
  pages/categories/[id]/index.tsx
  pages/items/[id]/index.tsx
  src/components/category/Category.tsx
  src/components/common/Col.tsx
  src/components/ddang/DDang.tsx
  src/types/styled.ts
Labels: feat

#31 refactor: 라우팅 방식 , state 전달 방식 변경
  pages/categories/[id]/index.tsx
  pages/index.tsx
  pages/items/[id]/index.tsx
  src/components/category/Card.tsx
  src/components/category/Category.tsx
  src/components/common/Img.tsx
  src/components/ddang/Card.tsx
  src/components/ddang/DDang.tsx
  src/components/slickSlider/Slide.tsx
  src/store/brand.ts
  src/store/category.ts
  src/store/index.ts
  src/styles/GlobalStyle.ts
Labels: refactor

#33 feat: 상품 상세정보 컴포넌트 추가
  pages/items/[id]/index.tsx
  public/images/Back.svg
  src/components/ddang/DDang.tsx
  src/components/items/Button.tsx
  src/components/items/Card.tsx
  src/components/items/Faq.tsx
  src/components/items/Header.tsx
  src/components/items/index.ts
  src/types/ddangData.ts
Labels: feat

#36 refactor: qas페이지에 close버튼 넣고, 스타일 변겅
  README.md
  pages/index.tsx
  pages/qas/index.tsx
  public/images/close.svg
  src/components/Mypage.tsx
Labels: refactor

#37 refactor: routing 방식 변경
  pages/qas/index.tsx
Labels: refactor
